
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fa
 */
public class BukuTerlambat extends javax.swing.JInternalFrame {
    private DefaultTableModel model; 

    /**
     * Creates new form BukuTerlamabat
     */
    Koneksi koneksi = new Koneksi();
    public BukuTerlambat() {
        initComponents();
        model = new DefaultTableModel();
        this.jTable1.setModel(model);
        model.addColumn("Id Peminjaman");
        model.addColumn("Id Anggota");
        model.addColumn("Nama");
        model.addColumn("Tanggal Kembali");
        ambil_data_tabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        private void ambil_data_tabel() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        koneksi.setKoneksi();
        try {
            koneksi.sql = "SELECT  * FROM peminjaman where tanggal_kembali < now() and not exists (select * from pengembalian where peminjaman.id_peminjaman=pengembalian.id_peminjaman)";
            koneksi.readData();
            while (koneksi.rs.next()) {
                Object[] o = new Object[4];
                o[0] = koneksi.rs.getString("id_peminjaman");
                o[1] = koneksi.rs.getString("member_id");
                o[2] = koneksi.rs.getString("nama");
                Date tgl_i = koneksi.rs.getDate("tanggal_kembali");
                DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                String tgl_in=dateFormat.format(tgl_i);
                o[3] = tgl_in;
                model.addRow(o);
            }
            koneksi.rs.close();
            koneksi.s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi kesalahan " + e.getMessage());
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Peminjaman", "Id Anggota", "Nama", "Tanggal Kembali"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
